name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.2
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.5.6
        env:
          CC_TEST_REPORTER_ID: d4dcb44147a2187c0008b61954886d98c935f320afcd97de44c50233a17deef4
        with:
          coverageCommand: npm run coverage
          coverageLocations: './coverage/lcov.info:lcov'
          debug: true
